### ISSUE TITLE
Add CVMFS to be available from notebook

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#171]
### Discussed in https://github.com/CoffeaTeam/coffea-casa/discussions/144

<div type='discussions-op-text'>

<sup>Originally posted by **oshadura** June 22, 2021</sup>
Question was asked by Furong Yan, while he was trying to use DAS tools, especially DAS client on coffea-casa.</div>

**Comment by clundst** [comment]
I'll add some note here as I spent some time trying to get this to work using a naive 'autofs' mount.  This *may* work if the containers ran in 'privileged' mode, which is a non-starter from my perspective.  This may require the inclusion of a cvmfs container that serves as a storage endpoint in k8s.  This has been done by others and that's probably the correct way.  I made zero progress getting that to actually 'go'.

**Comment by bbockelm** [comment]
Here's an example from the Tiger config repo where I added a patch to a container named `submit` to give it the CVMFS volume:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-submit
spec:
  template:
    spec:
      containers:
      - name: submit
        volumeMounts:
        - name: cvmfs-singularity
          mountPath: /cvmfs/singularity.opensciencegrid.org
      volumes:
      - name: cvmfs-singularity
        persistentVolumeClaim:
          claimName: osgdev-cvmfs-singularity
```

Would need to customize the `claimName` to match the local cluster's PVC names and the `mountPath` attribute for the actual desired repository name (e.g., `cms.cern.ch`).
