### ISSUE TITLE
Add support of multiple images at CMS & OD AF prod instances

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#247]
Current problem is that sidecar container is not defined per image and have strict versioning: 

```
singleuser:
      profileList:
        - display_name: "Coffea Base Image"
          description: "Coffea-casa build with coffea 0.7.8/dask/condor and cheese"
          kubespawner_override:
            image: coffeateam/coffea-casa:2021.10.28
        - display_name: "Coffea CC7 Base Image"
          description: "Coffea-casa TEST build with oidc support"
          kubespawner_override:
            image: hub.opensciencegrid.org/coffea-casa/coffea-casa-cc7:2021.12.10
      extraContainers:
      - name: dask-worker
        image: coffeateam/coffea-casa-analysis:2021.10.28
```
